spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_app
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tancong22110306@gmail.com
    password: lgbu phsg bfny jrvv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
